<?php

// Plugin definition
$plugin = array(
  'title' => t('Buss layout 5 rows 2 columns'),
  'category' => t('buss'),
  'icon' => 'buss.png',
  'theme' => 'buss',
  'css' => 'buss.css',
  'regions' => array(
    'right' => t('Right side'),
    'first_title' => t('First title'),
    'first_left_col' => t('First left col'),
    'first_right_col' => t('First right col'),
    'second_title' => t('Second title'),
    'second_left_col' => t('Second left col'),
    'second_right_col' => t('Second right col'),
    'third_title' => t('Third title'),
    'third_left_col' => t('Third left col'),
    'third_right_col' => t('Third right col'),
    'fourth_title' => t('Fourth title'),
    'fourth_left_col' => t('Fourth left col'),
    'fourth_right_col' => t('Fourth right col'),
    'fith_title' => t('Fith title'),
    'fith_left_col' => t('Fith left col'),
    'fith_right_col' => t('Fith right col')
  ),
);
